
version: '26.1.1'
services:
  database:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'bancoteste'   
      MYSQL_USER: 'bancoteste_user'
      MYSQL_PASSWORD: 'bancoteste_pass'      
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './volumes/mysql:/var/lib/mysql'
      - "./db.sql:/docker-entrypoint-initdb.d/1.sql"